### ISSUE TITLE
Running in debugger mode without networks and exposed port results with an invalid configurations

### ISSUE THREAD

**Issue by moshebe** [moshebe/gebug#28]
**Describe the bug**
Running in debugger mode without exposed ports results with an invalid `docker-compose.yml`

**To Reproduce**
1. Run `gebug init` and enable Debugger mode
2. Skip on the exposed-ports and network parts
3. Run `gebug start`
4. See the `.gebug/docker-compose.yml` error

**Expected behavior**
The debugger port should be on the `ports` section and not appear under `volumes`

**Screenshots/Snippets**
Example of an invalid generated configuration:

```
version: '3'
services:
  gebug-app:
    build:
      context: ..
      dockerfile: .gebug/Dockerfile
    cap_add:
      - SYS_PTRACE
    volumes:
      - ../:/src:ro
      - 40000:40000
```
